### ISSUE TITLE
Threads: Only shows 8 - but I have 24.

### ISSUE THREAD

**Issue by IngwiePhoenix** [sethfoxen/maxcsoGUI#2]
Using a AMD Ryzen 9 3900X, I can use up to 24 cores when compressing ISOs, even with Zopfli. However, when using the GUI, I have to enter my thread amount myself because it only shows up to 8.

Would be nice to have that fixed. :)

**Comment by sethfoxen** [comment]
Sorry for the SUPER late reply
8 threads is the max for my current processor, I set it as the dropdown maximum because of that. As you say, you CAN type any number into the box, andI left it that way for this very reason. I'm currently working out how to detect the number of threads a CPU can support, and listing THAT in the dropdown instead.

**Comment by sethfoxen** [comment]
Fixed in 0.4.0.0
